include: package:lints/recommended.yaml
linter:
  rules:
    prefer_single_quotes: false
    avoid_void_async: false
    prefer_interpolation_to_compose_strings: false
    avoid_print: false
    use_build_context_synchronously: false
    unnecessary_string_escapes: false
    avoid_dynamic_calls: false
    non_constant_identifier_names: false

analyzer:
  exclude:
    - lib/src/generated/frb_generated.dart
    - lib/src/generated/frb_generated.io.dart
    - lib/src/generated/frb_generated.dart
    - lib/src/generated/api/types.freezed.dart
    - README.md
    - cargokit/