name: ldk_node_flutter
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_rust_bridge: ">1.72.0 <= 1.72.1"
  freezed: ^2.3.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^7.2.2
  build_runner: ^2.3.3
flutter:
  plugin:
    platforms:
      android:
        package: io.ldk.f.ldk_node_flutter
        pluginClass: LdkNodeFlutterPlugin
      ios:
        pluginClass: LdkNodeFlutterPlugin

