name: ldk_node
description: A ready-to-go Lightning node library built using LDK and BDK.
version: 0.1.4
homepage: https://github.com/LtbLightning/ldk-node-flutter

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.17.1
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_rust_bridge: ">1.82.4 <= 1.82.6"
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  meta: ^1.10.0
  uuid: ^4.2.1
  path_provider: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  ffigen: ^9.0.1
  build_runner: ^2.4.4
  lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.ldk.f.ldk_node
        pluginClass: LdkNodePlugin
      ios:
        pluginClass: LdkNodePlugin
