[package]
name = "native"
version = "0.1.5"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies.external-lib]
path = "./ldk-lite"
package = "ldk-lite"

[build-dependencies]
flutter_rust_bridge_codegen = "1.51.0"





[dependencies]
rand = "0.8.5"
chrono = "0.4"
futures = "0.3"
serde_json = { version = "1.0" }
tokio = { version = "1", features = [ "full" ] }
flutter_rust_bridge = "1.51.0"
bitcoin = "0.29.2"
electrsd = { version = "0.22.0", features = ["legacy", "esplora_a33e97e1", "bitcoind_23_0"] }
electrum-client = "0.12.0"
lazy_static = "1.4.0"
once_cell = "1.16.0"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1