[package]
name = "ldk-node"
version = "0.2.1"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]


[build-dependencies]
flutter_rust_bridge_codegen = { version = "=1.82.6"  }


[dependencies]
flutter_rust_bridge = { version = "=1.82.6"  }

log = "0.4.19"
simplelog = "0.12.1"
lazy_static = "1.4.0"
once_cell = "1.18.0"
anyhow = { version = "1.0.71"}
ldk-node = { version = "= 0.2.1"  }


[profile.release]
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = 'abort'

