[package]
name = "rust_ldk_node"
version = "0.2.0"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]


[build-dependencies]
flutter_rust_bridge_codegen = { version = "=1.82.6"  }


[dependencies]
flutter_rust_bridge = { version = "=1.82.6"  }

log = "0.4.19"
simplelog = "0.12.1"
lazy_static = "1.4.0"
once_cell = "1.18.0"
# Merge pull request #170 from jbesraa/persist-inbound-channels
#ldk-node = { git = "https://github.com/lightningdevkit/ldk-node.git", rev = "fc09bfbfbe43bdedebacfc75305acaed2ad85446" }
anyhow= { version = "1.0.71"}
ldk-node = "0.2.0"

[profile.release]
opt-level = 'z'     # Optimize for size
lto = true          # Enable link-time optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations
strip = true    # Strip symbols from binary*
panic = 'abort'
